version: '3'

services:

  postgres:
    image: 'postgres:latest'
    ports:
      - "5436:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/